name: Schedule Worker
on:
  workflow_dispatch:
  push:
    branches:
      - master #2020年10月后github新建仓库默认分支改为main，注意更改
jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11.4'
      - run: python main.py

      - name: Archive files
        uses: actions/upload-artifact@v2
        with:
          name: compressed-files
          path: cs
